<a href="https://colab.research.google.com/github/swapnil-mergal/swapnil_mergal-23-27-27/blob/main/ASSN2_SWAPNIL_MERGAL_23_27_27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Q.1***
a) Create a variable named var1 that stores an array of numbers from 0 to 29,
inclusive. Print var1 and its shape. Hint : arange

b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function

c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.

d) Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)

e) Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.
(ii) Sum var3 over its third dimension and print the result.
(iii) Sum var3 over both its first and third dimensions and print the result.

f) Write code to do the following:
(i) Slice out the second row of var2 and print it.
(ii) Slice out the last column of var2 using the -1 notation and print it.
(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [23]:
# a)
import numpy as np
var1 = np.arange(30)
print(var1)
print(var1.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
(30,)


In [24]:
# b)
var2 = var1.reshape(6, 5)
print(var2)
print(var2.shape)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
(6, 5)


In [25]:
# c)
var3 = var1.reshape(3,2,5)
print(var3)
print(var3.shape)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
(3, 2, 5)


In [26]:
# d)
var2[1, 0] = -1
print(var1)  # Check if var1 changed
print(var3)  # Check if var3 changed


[ 0  1  2  3  4 -1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[[ 0  1  2  3  4]
  [-1  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [27]:
# e)
# Sum over the second dimension
sum_second_dim = var3.sum(axis=1)
print(sum_second_dim)

# Sum over the third dimension
sum_third_dim = var3.sum(axis=2)
print(sum_third_dim)

# Sum over first and third dimensions
sum_first_third_dim = var3.sum(axis=(0, 2))
print(sum_first_third_dim)


[[-1  7  9 11 13]
 [25 27 29 31 33]
 [45 47 49 51 53]]
[[ 10  29]
 [ 60  85]
 [110 135]]
[180 249]


In [28]:
# f)
# Slice out the second row of var2
print(var2[1, :])

# Slice out the last column using -1
print(var2[:, -1])

# Slice out the top-right 2x2 submatrix
print(var2[:2, -2:])


[-1  6  7  8  9]
[ 4  9 14 19 24 29]
[[3 4]
 [8 9]]


Q.2

a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.

c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )

d) You don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number generation
library, then generates a 50 × 5 matrix of standard normal

In [29]:
# a) Perform scalar broadcasting by adding 1 to an arange vector:
vector = np.arange(1, 11)
print(vector)


[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
# b) Create a 10x10 matrix where A_ij = i + j:
A = np.arange(1, 11) + np.arange(1, 11).reshape(10, 1)
print(A)


[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [31]:
# c) Create a dataset with 50 examples and 5 dimensions:
import numpy.random as npr
data = np.exp(npr.randn(50, 5))


In [44]:
# (d) - Compute the mean and standard deviation of each column in the dataset:
# Assuming the 'data' matrix is created as per
import numpy.random as npr

# Generate the dataset (from Q2(c))
data = np.exp(npr.randn(50, 5))

# Compute the mean and standard deviation for each column
mean_vec = data.mean(axis=0)  # Mean of each column (axis=0 means column-wise)
std_vec = data.std(axis=0)    # Standard deviation of each column

# Print the results
print("Column-wise Means:", mean_vec)
print("Column-wise Standard Deviations:", std_vec)


Column-wise Means: [1.46082828 1.6282052  1.4215538  1.44564843 1.78174846]
Column-wise Standard Deviations: [2.34812407 1.5380404  1.24478979 1.67234694 2.33167238]


In [32]:
# e) Compute the mean and standard deviation of each column:
mean_vec = data.mean(axis=0)
std_vec = data.std(axis=0)
print("Means:", mean_vec)
print("Standard Deviations:", std_vec)


Means: [1.29183101 1.63697479 2.14024513 1.95768865 1.50108589]
Standard Deviations: [1.28546587 2.07862606 3.10387218 2.29555056 2.0603849 ]


In [34]:
# f) Standardize the data:
normalized = (data - mean_vec) / std_vec
print("Normalized Data Mean:", normalized.mean(axis=0))
print("Normalized Data Std:", normalized.std(axis=0))


Normalized Data Mean: [-3.17523785e-16 -2.81996648e-16 -2.77555756e-17 -2.04281037e-16
 -3.77475828e-17]
Normalized Data Std: [1. 1. 1. 1. 1.]


Q.3

In [36]:
# a) Generate a Vandermonde matrix without a loop:
def vandermonde(N):
    vec = np.arange(N) + 1
    return vec ** np.arange(N).reshape(-1, 1)

vander = vandermonde(12)
print(vander)


[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            3            4            5
             6            7            8            9           10
            11           12]
 [           1            4            9           16           25
            36           49           64           81          100
           121          144]
 [           1            8           27           64          125
           216          343          512          729         1000
          1331         1728]
 [           1           16           81          256          625
          1296         2401         4096         6561        10000
         14641        20736]
 [           1           32          243         1024         3125
          7776        16807        32768        59049       100000
        161051       248832]
 [           1        

In [38]:
# b) Matrix-vector multiplication:
x = np.ones(12)
b = np.dot(vander, x)
print(b)


[1.20000000e+01 7.80000000e+01 6.50000000e+02 6.08400000e+03
 6.07100000e+04 6.30708000e+05 6.73595000e+06 7.33994040e+07
 8.12071910e+08 9.09203303e+09 1.02769131e+11 1.17068436e+12]


In [42]:
# c) Solve the system by inverting the matrix:import numpy.linalg as la
import numpy as np
import numpy.linalg as la  # Correct aliasing of numpy.linalg

# Invert the Vandermonde matrix
V_inv = la.inv(vander)

# Perform the matrix-vector multiplication
x_calc = np.dot(V_inv, b)

print(x_calc)


[1.40164465 0.59611278 1.00202715 1.00117254 0.9974848  1.00318933
 0.99717116 1.00180864 0.99918208 1.00024882 0.99995425 1.00000385]


In [43]:
# d) Solve using solve function:
x_solve = la.solve(vander, b)
print(x_solve)


[0.99997509 1.00022004 0.99910211 1.0022556  0.99613289 1.00472989
 0.99580438 1.00269135 0.99877921 1.00037229 0.99993139 1.00000578]
